spring.application.name=bookMyMovies

<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://kafka-c92c743-preethamshetty990-66c7.h.aivencloud.com:24423
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_bHNa__2mJQ6LbkdhwmB
=======
spring.datasource.url=jdbc:mysql://localhost:3306/bookmymovies
spring.datasource.username=root
spring.datasource.password=Prince@093
>>>>>>> 2462cb3 (Update frontend backend connection)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=Prince@093SuperSecureJWTSecretKeyMovieBooking2026
jwt.expiration=86400000

server.port=${PORT:8080}
