spring.application.name=bookMyMovies

spring.datasource.url=jdbc:mysql://mysql-358cb9ac-bookmymovies.k.aivencloud.com:26755/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ZQ7y9p5NNI8sMdM88Uy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=BookMyMoviesIn2026ThisIsMySecretKeyForJWTAuthentication
jwt.expiration=86400000

server.port=${PORT:8080}
